# Permalinks
permalink:           pretty

# Setup
title:               我的数学笔记本
tagline:             Myzhang1029's middle school math notebook
url:                 http://myzhang1029.gitlab.io
baseurl:             "/mnb"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Zhang Maiyun
  url:               https://myzhang1029.gitlab.io
  email:             myzhang1029@hotmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://gitlab.com/myzhang1029/mnb

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

markdown: kramdown
